node {
    
    notify ('START')
    stage('checkout') {
        git 'https://github.com/akmaharshi/jenkins.git'
    }

    def project_path = "spring-boot-samples/spring-boot-sample-atmosphere"

    dir(project_path) {
        stage('compile,test and package') {
            sh 'mvn clean package'
        }
    
        stage('archival') {
            archiveArtifacts 'target/*.jar'
        }

        stage('unit test') {
            junit 'target/surefire-reports/*.xml'

        }
    }
}

def notify(status){
    emailext (
      to: "anil.maharshi@gmail.com",
      subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
      body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
        <p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
    )
}


